<?php namespace Application\WebAdmin;

use Eternity\Routing\Router;
use RedFox\Entity\Attachment\ThumbnailResponder;

/**
 * @domain admin.@
 */
class Site extends \Eternity\Application\WebApp {

	public function __construct() {
		session_start();
	}

//	protected function init() {
//		parent::init(); // TODO: Change the autogenerated stub
//		ServiceManager::bind('HandyResponderDistFolder')->value('/dist/admin/');
//		ServiceManager::bind('HandyResponderCustomTagNamespace')->value('App.Site.Admin.Customtag');
//		ServiceManager::bind('AuthService')->sharedService(\App\Site\Admin\Service\AuthService::class);
//	}

	function run() {
		$router = Router::Service();

		$router->post('/login', Action\AuthAction::class, ['method'=>'login'])();
		$router->pipe(Middleware\AuthCheck::class);
		$router->post('/login', Action\AuthAction::class, ['method'=>'login'])();
		$router->post('/logout', Action\AuthAction::class, ['method'=>'logout'])();

		$router->get('/thumbnails/*', ThumbnailResponder::class)();
		$router->get('/menu', Action\GetMenu::class)();

		$router->get('/', Page\Index::class)();

		Form\UserFormDescriptor::createRoutes($router);
	}
}


